### ISSUE TITLE
Radon

### ISSUE THREAD

**Issue by jjanderson** [Limych/ha-iaquk#1]
**Is your feature request related to a problem? Please describe.**

No Issues, love the component and thanks for all your hard work on this

**Describe the solution you'd like**

Could you please add Radon (Bq/m3) as an optional sensor?

Radon, although excess exposure is limited to certain areas in the UK, is the 2nd largest cause of Lung Cancer after smoking with roughly 1,100 lung cancer deaths  attributed to radon exposure in the home per year in the UK.

Thanks again for making this!

**Comment by Limych** [comment]
I wanted to add it, but I could not understand in what units the sensors usually return its value.
Could you clarify this question for me.

**Comment by Limych** [comment]
I've created feauture branch for Radon. You can test it by installing this version manually on top of the original one.

**Comment by jjanderson** [comment]
Hi,

I installed this branch, but not sure if this includes the bug for unknown values that I raised. I don't think it does as now I am getting at least one value reading as per the image. This does however seem to indicate that the Radon component is successfully coming through as Kitchen is where I have the radon sensor:

![image](https://user-images.githubusercontent.com/1214287/73458398-1cafc900-436d-11ea-8160-216807695273.png)


Here is my config.yaml entry:

```
iaquk:
  kitchen:
    name: "Kitchen"
    sources:
      temperature: sensor.kitchen_multisensor_temperature
      humidity: sensor.kitchen_multisensor_relative_humidity
      co2: sensor.airthings_co2
      tvoc: sensor.airthings_voc
      radon: sensor.airthings_short_term_radon
    sensors:
      - iaq_level
  finn:
    name: "Finn"
    sources:
      temperature: sensor.finn_bedroom_ave_temp
      humidity: sensor.finn_ave_humidity
      co2: sensor.netatmo_bedroom_co2
#      tvoc: sensor.finn_tvoc
    sensors:
      - iaq_level
  jake:
    name: "Jake"
    sources:
      temperature: sensor.jake_bedroom_ave_temp
      humidity: sensor.jake_ave_humidity
      co2: sensor.netatmo_jake_co2
#      tvoc: sensor.jake_tvoc
    sensors:
      - iaq_level
  lounge:
    name: "Lounge"
    sources:
      temperature: sensor.downstairs_thermostat_temperature
      humidity: sensor.downstairs_thermostat_humidity
#      co2: sensor.lounge_eco2
#      tvoc: sensor.lounge_tvoc
    sensors:
      - iaq_level
  bedroom:
    name: "Bedroom"
    sources:
      temperature: sensor.master_bedroom_ave_temp
      humidity: sensor.netatmo_bedroom_humidity
#      co2: sensor.bedroom_eco2
#      tvoc: sensor.bedroom_tvoc
    sensors:
      - iaq_level
```

Additionally, here are my entries for each of the active sensors for Finn's Room:


`sensor.finn_bedroom_ave_temp | 19.77 | count_sensors: 3 max_value: 20.6 mean: 19.77 min_value: 19.2 last: 20.6 unit_of_measurement: °C friendly_name: Finn Bedroom Ave Temp icon: mdi:thermometer custom_ui_state_card: state-card-custom-ui device_class: temperature`
-- | -- | --


`sensor.finn_ave_humidity | 50.77 | count_sensors: 3 max_value: 55.3 mean: 50.77 min_value: 43 last: 43 unit_of_measurement: % friendly_name: Finn Ave Humidity icon: mdi:water-percent custom_ui_state_card: state-card-custom-ui device_class: humidity`
-- | -- | --


`sensor.netatmo_bedroom_co2 | 407 | unit_of_measurement: ppm friendly_name: netatmo Finn Room Bedroom CO2 icon: mdi:periodic-table-co2 custom_ui_state_card: state-card-custom-ui`
-- | -- | --

This is a reallly great component, thanks for making it... let me know if you need any more info or anything.

Thanks
