### ISSUE TITLE
no history found for iaq level

### ISSUE THREAD

**Issue by Progaros** [Limych/ha-iaquk#105]
**Environment**

- Home Assistant Core release with the issue: newest
- This custom component release with the issue: newest
- Last working this custom component release (if known): none (downloaded 1 week ago)
- Operating environment (Home Assistant/Supervisor/Docker/venv): newest

**Describe the bug**

```
Zimmer Indoor Air Quality Level
Fair (6 minutes ago)
**History: No statistics found.**
```

**Configuration.yaml**
```yaml

iaquk:
  zimmer:
    sources:
      temperature: sensor.temperature
      humidity: sensor.humidity
      co2: sensor.scd30_co2
    sensors:
      - iaq_level
      - iaq_index

history:

recorder:
  purge_keep_days: 10

```

**Steps to Reproduce**

**Expected behavior**

history of sensor with recent states

**Debug log**

```text

Add your logs here.

```

**Additional context**
