### ISSUE TITLE
Device class None

### ISSUE THREAD

**Issue by cinghialino** [Limych/ha-iaquk#109]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

Sensor sensor.iaquk_home_indoor_air_quality_level has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: Good (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Configuration.yaml**
```yaml

iaquk:
  air_quality_index:
    name: "Home"
    sources:
      temperature: sensor.average_temperature
      humidity: sensor.average_humidity
      co2: sensor.vindriktning1_co2_level
#      tvoc: sensor.kitchen_tvoc
      pm:
        - sensor.vindriktning1_particulate_matter_2_5um_concentration
        - sensor.pure_cool_link_particulates
    sensors:
      - iaq_level
      - iaq_index

```

**Steps to Reproduce**
update HA to 2023.02

**Expected behavior**
not having an error in the log

**Debug log**

```text

Sensor sensor.iaquk_home_indoor_air_quality_level has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: Good (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

```

**Additional context**

none
