### ISSUE TITLE
"Unknown" Values

### ISSUE THREAD

**Issue by jjanderson** [Limych/ha-iaquk#2]
Hi,

I installed via HACS.

I then added the following to my configuration.yaml

```
iaquk:
  kitchen:
    name: "Kitchen"
    sources:
      temperature: sensor.kitchen_temperature
      humidity: sensor.kitchen_multisensor_relative_humidity
      co2: sensor.airthings_co2
      tvoc: sensor.airthings_voc
    sensors:
      - iaq_level
  finn:
    name: "Finn"
    sources:
      temperature: sensor.finn_bedroom_ave_temp
      humidity: sensor.finn_ave_humidity
      co2: sensor.netatmo_bedroom_co2
#      tvoc: sensor.finn_tvoc
    sensors:
      - iaq_level
  jake:
    name: "Jake"
    sources:
      temperature: sensor.jake_bedroom_ave_temp
      humidity: sensor.jake_ave_humidity
      co2: sensor.netatmo_jake_co2
#      tvoc: sensor.jake_tvoc
    sensors:
      - iaq_level
  lounge:
    name: "Lounge"
    sources:
      temperature: sensor.downstairs_thermostat_temperature
      humidity: sensor.downstairs_thermostat_humidity
#      co2: sensor.lounge_eco2
#      tvoc: sensor.lounge_tvoc
    sensors:
      - iaq_level
  bedroom:
    name: "Bedroom"
    sources:
      temperature: sensor.master_bedroom_ave_temp
      humidity: sensor.netatmo_bedroom_humidity
#      co2: sensor.bedroom_eco2
#      tvoc: sensor.bedroom_tvoc
    sensors:
      - iaq_level
```

I am not however getting any readings.

I have checked the individual sensors and they are all pulling values through,

![image](https://user-images.githubusercontent.com/1214287/73181086-7ebec300-410e-11ea-94be-e6d5eaa5e075.png)

**Debug log**

```text

Add your logs here.

```
2020-01-27 13:50:23 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:644
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 656, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 364, in async_run_job
    target(*args)
  File "/config/custom_components/iaquk/__init__.py", line 137, in sensor_startup
    sensor_state_listener(None, None, None)  # Force first update
  File "/config/custom_components/iaquk/__init__.py", line 123, in sensor_state_listener
    self.update()
  File "/config/custom_components/iaquk/__init__.py", line 181, in update
    index = self.__getattribute__('_%s_index' % src)
  File "/config/custom_components/iaquk/__init__.py", line 323, in _pm_index
    for eid in entity_ids:
TypeError: 'NoneType' object is not iterable
2020-01-27 13:50:23 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:644
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 656, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 364, in async_run_job
    target(*args)
  File "/config/custom_components/iaquk/__init__.py", line 137, in sensor_startup
    sensor_state_listener(None, None, None)  # Force first update
  File "/config/custom_components/iaquk/__init__.py", line 123, in sensor_state_listener
    self.update()
  File "/config/custom_components/iaquk/__init__.py", line 181, in update
    index = self.__getattribute__('_%s_index' % src)
  File "/config/custom_components/iaquk/__init__.py", line 323, in _pm_index
    for eid in entity_ids:
TypeError: 'NoneType' object is not iterable
2020-01-27 13:50:23 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:644
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 656, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 364, in async_run_job
    target(*args)
  File "/config/custom_components/iaquk/__init__.py", line 137, in sensor_startup
    sensor_state_listener(None, None, None)  # Force first update
  File "/config/custom_components/iaquk/__init__.py", line 123, in sensor_state_listener
    self.update()
  File "/config/custom_components/iaquk/__init__.py", line 181, in update
    index = self.__getattribute__('_%s_index' % src)
  File "/config/custom_components/iaquk/__init__.py", line 323, in _pm_index
    for eid in entity_ids:
TypeError: 'NoneType' object is not iterable
2020-01-27 13:50:23 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:644
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 656, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 364, in async_run_job
    target(*args)
  File "/config/custom_components/iaquk/__init__.py", line 137, in sensor_startup
    sensor_state_listener(None, None, None)  # Force first update
  File "/config/custom_components/iaquk/__init__.py", line 123, in sensor_state_listener
    self.update()
  File "/config/custom_components/iaquk/__init__.py", line 181, in update
    index = self.__getattribute__('_%s_index' % src)
  File "/config/custom_components/iaquk/__init__.py", line 323, in _pm_index
    for eid in entity_ids:
TypeError: 'NoneType' object is not iterable
2020-01-27 13:50:23 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:644
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 656, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 364, in async_run_job
    target(*args)
  File "/config/custom_components/iaquk/__init__.py", line 137, in sensor_startup
    sensor_state_listener(None, None, None)  # Force first update
  File "/config/custom_components/iaquk/__init__.py", line 123, in sensor_state_listener
    self.update()
  File "/config/custom_components/iaquk/__init__.py", line 181, in update
    index = self.__getattribute__('_%s_index' % src)
  File "/config/custom_components/iaquk/__init__.py", line 323, in _pm_index
    for eid in entity_ids:
TypeError: 'NoneType' object is not iterable
```

**Additional context**

Add any other context about the problem here.
